import { StyleSheet, type TextStyle, type ViewStyle } from "react-native";
import type { IosStyleFactory, ThemeColors } from "./theme";

const page: ViewStyle = {
  width: "100%",
  maxWidth: 760,
  alignSelf: "center",
  paddingHorizontal: 20,
  paddingTop: 24,
  paddingBottom: 32,
};
const largeTitle: TextStyle = {
  fontSize: 32,
  lineHeight: 40,
  fontWeight: "700",
  letterSpacing: -0.7,
};
const sectionTitle: TextStyle = {
  fontSize: 20,
  lineHeight: 26,
  fontWeight: "700",
  letterSpacing: -0.3,
};
const body: TextStyle = { fontSize: 17, lineHeight: 26 };
const caption: TextStyle = {
  fontSize: 13,
  lineHeight: 20,
  fontWeight: "400",
  letterSpacing: 0,
};
const primary: ViewStyle = {
  borderRadius: 14,
  minHeight: 50,
  paddingHorizontal: 16,
};
const sheet: ViewStyle = {
  maxWidth: 640,
  alignSelf: "center",
  borderRadius: 24,
  overflow: "hidden",
};
const hairline = StyleSheet.hairlineWidth;
const panel = (c: ThemeColors): ViewStyle => ({
  backgroundColor: c.surface,
  borderWidth: 0,
  borderRadius: 16,
});
const secondary = (c: ThemeColors): ViewStyle => ({
  backgroundColor: c.surfaceMuted,
  borderWidth: 0,
  borderRadius: 12,
  minHeight: 44,
});

// Screen-specific overrides keep presentation explicit and shared business logic intact.
export const iosStyles: Record<string, IosStyleFactory> = {
  shell: (c) => ({
    tabBar: {
      backgroundColor: c.chrome,
      borderTopWidth: hairline,
      paddingTop: 6,
      paddingBottom: 4,
    },
    tab: { minHeight: 54, gap: 4 },
    tabIcon: { color: c.textMuted, fontSize: 23, height: 25, lineHeight: 25 },
    tabLabel: { color: c.textMuted, fontSize: 11, fontWeight: "500" },
    activeTabLabel: { color: c.brand, fontWeight: "600" },
    aiProgressCard: {
      ...panel(c),
      borderWidth: hairline,
      borderColor: c.border,
      borderRadius: 20,
    },
    aiProgressCollapsed: {
      ...panel(c),
      borderColor: c.border,
      borderWidth: hairline,
    },
    aiProgressTools: { minHeight: 44 },
    aiProgressMessage: caption,
    updateCard: { ...panel(c), width: "100%", maxWidth: 440, padding: 24 },
    updateTitle: largeTitle,
    updateButton: primary,
  }),
  auth: (c) => ({
    content: { ...page, maxWidth: 460, paddingTop: 36 },
    hero: { paddingTop: 12, paddingBottom: 28, gap: 12 },
    kicker: { ...caption, color: c.textMuted, marginTop: 16 },
    title: { ...largeTitle, fontSize: 34, lineHeight: 42 },
    subtitle: { ...body, color: c.textMuted },
    card: { ...panel(c), padding: 20, borderRadius: 20 },
    segmented: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      padding: 3,
      marginBottom: 20,
    },
    segment: { minHeight: 38, paddingVertical: 8, borderRadius: 8 },
    activeSegment: {
      backgroundColor: c.surface,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
    },
    activeSegmentText: { color: c.text, fontWeight: "600" },
    label: { fontSize: 15, fontWeight: "500", marginBottom: 8, marginTop: 12 },
    input: {
      backgroundColor: c.background,
      borderWidth: 0,
      borderRadius: 12,
      minHeight: 52,
    },
    primaryButton: { ...primary, marginTop: 24 },
    primaryButtonText: { fontSize: 17, fontWeight: "600" },
    note: { ...caption, color: c.textMuted, marginTop: 24 },
  }),
  certificate: (c) => ({
    content: page,
    hero: { paddingTop: 4, paddingBottom: 24 },
    kicker: { ...caption, color: c.textMuted, fontWeight: "400" },
    title: largeTitle,
    subtitle: { ...body, fontSize: 15, lineHeight: 24 },
    list: { gap: 12 },
    certificateCard: { ...panel(c), minHeight: 104, padding: 16 },
    selectedCertificateCard: {
      backgroundColor: c.brandSoft,
      borderWidth: 1,
      borderColor: c.brand,
    },
    badge: { borderRadius: 12, width: 44, height: 44 },
    name: { fontSize: 17, lineHeight: 25, fontWeight: "600" },
    meta: caption,
    backButton: { minHeight: 44, justifyContent: "center" },
    backText: { fontSize: 17, fontWeight: "400" },
    arrow: { color: c.textFaint, fontSize: 18 },
  }),
  overview: (c) => ({
    page,
    title: { ...largeTitle, fontSize: 30, lineHeight: 38 },
    kicker: { ...caption, marginBottom: 6 },
    brandGlyph: { color: c.brand, fontSize: 26 },
    coverage: { ...panel(c), padding: 20, marginTop: 24, marginBottom: 16 },
    coverageValue: {
      fontSize: 44,
      fontWeight: "700",
      letterSpacing: -1.5,
      fontVariant: ["tabular-nums"],
    },
    coverageDetail: { ...caption, flexShrink: 1 },
    footnote: caption,
    daily: { ...panel(c), padding: 20, gap: 16 },
    dailyLabel: { ...caption, color: c.textMuted },
    dailyTitle: { fontSize: 18, lineHeight: 26, color: c.text, marginTop: 4 },
    dailyCount: { color: c.brand, fontSize: 28, fontVariant: ["tabular-nums"] },
    dailyUnit: { color: c.textMuted, fontSize: 13 },
    dailyButton: { ...primary, backgroundColor: c.action },
    dailyButtonText: { color: c.white, fontSize: 17, fontWeight: "600" },
    dailyArrow: { color: c.white },
    metrics: {
      ...panel(c),
      marginTop: 16,
      paddingVertical: 20,
      borderBottomWidth: 0,
    },
    metricValue: { fontSize: 24, fontVariant: ["tabular-nums"] },
    metricLabel: { ...caption, textAlign: "center" },
    sectionTitle,
    sectionHead: { marginTop: 28, marginBottom: 12 },
    link: { fontSize: 15 },
    chapterRow: {
      backgroundColor: c.surface,
      padding: 16,
      borderRadius: 14,
      borderBottomWidth: 0,
      marginBottom: 8,
      gap: 10,
    },
    rowTitle: { fontSize: 17, lineHeight: 25, fontWeight: "600" },
    rowMeta: caption,
    quick: { ...panel(c), minHeight: 88, padding: 16 },
    quickTitle: { fontSize: 17, lineHeight: 24 },
    weakRow: { ...panel(c), padding: 16, gap: 10, marginBottom: 10 },
    selectedWeak: {
      backgroundColor: c.brandSoft,
      borderWidth: 1,
      borderColor: c.brand,
    },
    primary: { ...primary, marginTop: 20 },
    primaryText: { fontSize: 17, fontWeight: "600" },
    filterRow: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      padding: 3,
      gap: 3,
    },
    filter: {
      flex: 1,
      minHeight: 40,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    filterActive: { backgroundColor: c.surface },
    filterText: { fontSize: 15 },
    filterTextActive: { color: c.text },
    questionRow: {
      backgroundColor: c.surface,
      borderRadius: 14,
      borderBottomWidth: 0,
      marginBottom: 8,
      padding: 16,
    },
    questionTitle: { fontSize: 16, lineHeight: 25 },
    emptyTitle: sectionTitle,
    empty: { fontSize: 15, lineHeight: 24 },
  }),
  practiceHub: (c) => ({
    page,
    title: largeTitle,
    headingMeta: caption,
    progressLabel: caption,
    modeRow: { gap: 10 },
    mode: { ...panel(c), padding: 12 },
    modeSelected: {
      backgroundColor: c.brandSoft,
      borderWidth: 1,
      borderColor: c.brand,
    },
    modeTitle: { fontSize: 15, lineHeight: 22, fontWeight: "600" },
    modeHint: caption,
    modeGlyph: { fontSize: 24 },
    library: { ...panel(c), padding: 14 },
    libraryTitle: { fontSize: 15, lineHeight: 22, fontWeight: "600" },
    libraryMeta: caption,
    libraryIcon: { width: 32, height: 32, borderRadius: 9 },
    noticeText: caption,
    sectionTitle,
    meta: caption,
    link: { fontSize: 15 },
    searchBox: {
      backgroundColor: c.surfaceMuted,
      borderWidth: 0,
      minHeight: 48,
      borderRadius: 12,
    },
    searchInput: { fontSize: 17, paddingVertical: 12 },
    searchHint: caption,
    chapter: { ...panel(c), marginBottom: 12 },
    chapterOpen: { borderWidth: 1, borderColor: c.brand },
    chapterHeading: { paddingHorizontal: 16, paddingTop: 12 },
    chapterTitle: { fontSize: 17, lineHeight: 25, fontWeight: "600" },
    chapterBottom: { paddingHorizontal: 16, paddingBottom: 12 },
    chapterStart: { ...secondary(c), paddingHorizontal: 12 },
    chapterStartText: { fontSize: 14 },
    children: { backgroundColor: c.surface, paddingHorizontal: 16 },
    sectionName: { fontSize: 15, lineHeight: 24 },
    pointName: { fontSize: 15, lineHeight: 24 },
    pointAction: { fontSize: 14 },
    dailyAll: { ...panel(c), padding: 16 },
    dailyAllTitle: { fontSize: 17 },
    footer: caption,
  }),
  tabs: (c) => ({
    content: { ...page, backgroundColor: c.background },
    compactContent: { paddingTop: 16 },
    profileContent: { paddingTop: 24 },
    header: { marginBottom: 20 },
    eyebrow: { ...caption, color: c.textMuted },
    screenTitle: largeTitle,
    primaryAction: primary,
    primaryActionText: { fontSize: 17, fontWeight: "600" },
    modeSwitch: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      padding: 3,
      borderWidth: 0,
    },
    modeButton: { borderRadius: 8, minHeight: 44 },
    activeModeButton: { backgroundColor: c.surface },
    activeModeButtonText: { color: c.text },
    modeButtonText: { fontSize: 15, fontWeight: "500" },
    questionCard: { ...panel(c), padding: 20, gap: 16 },
    questionText: {
      fontSize: 19,
      lineHeight: 31,
      fontWeight: "500",
      paddingRight: 0,
    },
    questionUtilityIcons: {
      position: "relative",
      bottom: 0,
      right: 0,
      justifyContent: "flex-end",
      gap: 8,
    },
    questionType: {
      backgroundColor: c.surfaceMuted,
      color: c.textMuted,
      borderRadius: 6,
    },
    questionKnowledge: caption,
    questionIconButton: {
      width: 44,
      height: 44,
      backgroundColor: c.background,
      borderRadius: 22,
    },
    questionOption: {
      minHeight: 58,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      padding: 14,
    },
    questionOptionText: { fontSize: 17, lineHeight: 26, fontWeight: "400" },
    selectedOption: { backgroundColor: c.brandSoft, borderColor: c.brand },
    correctOption: { backgroundColor: c.successSoft, borderColor: c.success },
    wrongOption: { backgroundColor: c.warningSoft, borderColor: c.warning },
    optionLetter: { backgroundColor: c.background },
    optionLetterText: { color: c.textMuted },
    correctOptionLetter: { backgroundColor: c.successSoft },
    wrongOptionLetter: { backgroundColor: c.warningSoft },
    selectedOptionLetter: { backgroundColor: c.brandSoft },
    feedbackGood: { backgroundColor: c.successSoft, padding: 16 },
    feedbackBad: { backgroundColor: c.warningSoft, padding: 16 },
    feedbackText: { fontSize: 16, lineHeight: 26 },
    shortAnswerInput: {
      ...body,
      backgroundColor: c.background,
      borderRadius: 12,
    },
    aiUtilityButton: { ...secondary(c), borderColor: c.border },
    aiUtilityButtonText: { fontSize: 15, fontWeight: "500" },
    aiToolButton: { ...secondary(c), paddingHorizontal: 12 },
    aiToolButtonText: { fontSize: 14, fontWeight: "500" },
    aiResponseCard: {
      ...panel(c),
      padding: 16,
      borderWidth: 1,
      borderColor: c.border,
      gap: 8,
    },
    aiResponseText: { fontSize: 16, lineHeight: 26 },
    modalBackdrop: { backgroundColor: c.overlay, padding: 12 },
    settingsModal: { ...sheet, backgroundColor: c.background },
    reportModal: sheet,
    nameModal: sheet,
    sponsorModal: sheet,
    modalTitle: { fontSize: 22, lineHeight: 30, fontWeight: "700" },
    modalIntro: { fontSize: 15, lineHeight: 24 },
    modalCloseButton: {
      ...secondary(c),
      backgroundColor: c.surface,
      minHeight: 44,
      paddingHorizontal: 12,
      borderRadius: 22,
    },
    modalCloseText: { fontSize: 15, fontWeight: "500" },
    modalPrimaryButton: primary,
    modalPrimaryText: { fontSize: 17, fontWeight: "600" },
    modalSecondaryButton: secondary(c),
    modalSecondaryText: { fontSize: 17, fontWeight: "400" },
    settingsSectionTitle: {
      fontSize: 15,
      fontWeight: "500",
      color: c.textMuted,
      marginTop: 12,
    },
    settingsModalScroll: { padding: 20, gap: 16 },
    appearanceOptions: { ...panel(c), overflow: "hidden", gap: 0 },
    appearanceOption: {
      backgroundColor: c.surface,
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: hairline,
      minHeight: 64,
      borderBottomColor: c.border,
      paddingHorizontal: 16,
    },
    appearanceOptionActive: {
      backgroundColor: c.brandSoft,
      borderColor: c.border,
    },
    appearanceOptionText: { fontSize: 17, fontWeight: "400" },
    appearanceOptionHint: caption,
    appearanceOptionTextActive: { color: c.text },
    appearanceCheck: { color: c.brand, fontSize: 20 },
    settingsInput: {
      backgroundColor: c.surface,
      borderWidth: 0,
      borderRadius: 12,
      minHeight: 50,
      fontSize: 17,
    },
    soundStyleOption: { ...panel(c), minHeight: 64 },
    soundVolumeOption: { ...secondary(c), minHeight: 44 },
    soundPreviewButton: { ...secondary(c), backgroundColor: c.surface },
    settingsHint: caption,
    profileCard: { ...panel(c), padding: 20, gap: 16 },
    profileKicker: caption,
    profileName: { fontSize: 23, lineHeight: 30, fontWeight: "600" },
    profileMeta: { fontSize: 14, lineHeight: 22 },
    avatar: { height: 56, width: 56, borderRadius: 28 },
    profileCertificateButton: {
      borderWidth: 0,
      backgroundColor: c.background,
      minHeight: 44,
      borderRadius: 22,
      paddingHorizontal: 12,
    },
    profileCertificateText: { fontSize: 15, fontWeight: "500" },
    profileSyncText: caption,
    profileSyncDot: { backgroundColor: c.success },
    profileSyncRow: { borderTopWidth: hairline, paddingTop: 12 },
    profileSectionTitle: sectionTitle,
    profileSectionHint: { display: "none" },
    profileSectionHeader: { marginBottom: 4 },
    profileShortcut: { ...panel(c), minHeight: 120, padding: 16, gap: 8 },
    profileShortcutTitle: { fontSize: 17, fontWeight: "600" },
    profileShortcutMeta: caption,
    profileShortcutGlyph: { fontSize: 19 },
    profileShortcutIcon: { width: 36, height: 36, borderRadius: 10 },
    settingsCard: { ...panel(c), paddingHorizontal: 16, overflow: "hidden" },
    settingRow: { minHeight: 64, borderBottomWidth: hairline, gap: 12 },
    settingTitle: {
      fontSize: 17,
      lineHeight: 26,
      fontWeight: "400",
      flexShrink: 1,
    },
    settingValue: { fontSize: 14, lineHeight: 22 },
    settingValueWrap: { flexShrink: 1 },
    settingArrow: { color: c.textFaint, fontSize: 16 },
    logoutButton: { ...panel(c), minHeight: 54 },
    logoutText: { fontSize: 17, fontWeight: "400" },
    aboutHero: { backgroundColor: c.brandSoft },
    aboutHeroTitle: { color: c.text, fontSize: 20 },
    aboutHeroMark: { backgroundColor: c.action, borderWidth: 0 },
    aboutHeroText: { color: c.textMuted, fontSize: 15, lineHeight: 24 },
    completedCard: { ...panel(c), padding: 24 },
    completedTitle: sectionTitle,
    emptyCard: panel(c),
    emptyTitle: sectionTitle,
  }),
  exam: (c) => ({
    page,
    title: largeTitle,
    kicker: caption,
    subtitle: { fontSize: 15, lineHeight: 24 },
    sectionTitle,
    quantityRow: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      gap: 3,
      padding: 3,
    },
    quantity: {
      backgroundColor: "transparent",
      borderWidth: 0,
      minHeight: 44,
      borderRadius: 8,
    },
    quantityText: { fontSize: 15 },
    selected: { backgroundColor: c.surface, borderWidth: 0 },
    selectedText: { color: c.text, fontWeight: "600" },
    chapter: { ...panel(c), padding: 16, minHeight: 76, marginBottom: 8 },
    chapterSelected: {
      backgroundColor: c.brandSoft,
      borderWidth: 1,
      borderColor: c.brand,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderColor: c.textFaint,
    },
    rowTitle: { fontSize: 17, lineHeight: 25 },
    meta: caption,
    footnote: caption,
    resume: { ...panel(c), padding: 16 },
    historyRow: { ...panel(c), padding: 16, marginBottom: 8 },
    primary,
    primaryText: { fontSize: 17, fontWeight: "600" },
    setupFooter: {
      backgroundColor: c.chrome,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderTopWidth: hairline,
    },
    examHeader: {
      backgroundColor: c.chrome,
      borderBottomWidth: hairline,
      borderBottomColor: c.border,
    },
    timer: {
      color: c.brand,
      fontSize: 24,
      fontWeight: "600",
      fontVariant: ["tabular-nums"],
    },
    questionPage: { ...page, paddingTop: 20 },
    examQuestion: { fontSize: 19, lineHeight: 31, fontWeight: "500" },
    option: {
      backgroundColor: c.surface,
      borderRadius: 12,
      borderColor: c.border,
      minHeight: 58,
      padding: 14,
    },
    optionText: { fontSize: 17, lineHeight: 26 },
    optionSelected: { backgroundColor: c.brandSoft, borderColor: c.brand },
    examFooter: {
      backgroundColor: c.chrome,
      borderTopWidth: hairline,
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    secondary: secondary(c),
    next: primary,
    secondaryText: { fontSize: 17, fontWeight: "400" },
    modalBackdrop: { backgroundColor: c.overlay, padding: 12 },
    sheet: { ...sheet, padding: 20, gap: 16 },
    gridCell: { minHeight: 44, minWidth: 44, borderRadius: 12 },
    resultScore: { ...panel(c), padding: 24 },
    reviewRow: { ...panel(c), padding: 16, marginBottom: 12 },
    explanation: { fontSize: 16, lineHeight: 27 },
  }),
  vip: (c) => ({
    content: page,
    title: largeTitle,
    eyebrow: caption,
    heading: { marginBottom: 20, alignItems: "flex-start", gap: 12 },
    headingCopy: { flex: 1, minWidth: 0 },
    redeemLink: { paddingTop: 8, paddingVertical: 0, justifyContent: "center" },
    redeemLinkText: { fontSize: 15 },
    accountRow: { ...panel(c), padding: 16 },
    accountLabel: caption,
    accountMeta: caption,
    accountActionText: { fontSize: 15 },
    usageSection: { ...panel(c), marginTop: 16, marginBottom: 16, padding: 16 },
    studyEntry: { ...panel(c), marginTop: 16, padding: 20, borderLeftWidth: 0 },
    studyTitle: sectionTitle,
    studyIntro: { fontSize: 17, lineHeight: 27 },
    quotaLabel: caption,
    quotaFootnote: caption,
    sectionTitle: { fontSize: 17, lineHeight: 24 },
    checkInRow: { ...panel(c), padding: 16 },
    checkInTitle: { fontSize: 17, lineHeight: 24 },
    checkInMeta: caption,
    checkInButton: { ...primary, minHeight: 44 },
    checkInButtonText: { fontSize: 15 },
    plan: { borderRadius: 16, minHeight: 154, paddingHorizontal: 12 },
    planName: { fontSize: 16, fontWeight: "600" },
    planDescription: caption,
    planQuantity: caption,
    price: { fontSize: 29, fontWeight: "700" },
    benefits: { ...panel(c), padding: 20 },
    benefitTitle: { fontSize: 17, lineHeight: 25 },
    benefitDetail: caption,
    benefitFooter: { flexWrap: "wrap", gap: 6 },
    benefitFooterText: caption,
    primary,
    primaryText: { fontSize: 17, fontWeight: "600" },
    purchaseHint: caption,
    apiSection: { ...panel(c), marginTop: 20, paddingHorizontal: 16 },
    apiTitle: { fontSize: 17 },
    apiMeta: caption,
  }),
  aiDraft: (c) => ({
    content: page,
    headerTitle: { fontSize: 22, lineHeight: 30 },
    headerSubtitle: caption,
    hero: { ...panel(c), padding: 20 },
    heroTitle: { ...largeTitle, color: c.text, fontSize: 28, lineHeight: 36 },
    heroEyebrow: { ...caption, color: c.textMuted },
    heroDescription: { fontSize: 15, lineHeight: 24, color: c.textMuted },
    heroBadge: { backgroundColor: c.brandSoft },
    heroBadgeText: { color: c.brand },
    heroTopic: { backgroundColor: c.background, borderWidth: 0 },
    heroTopicLabel: { ...caption, color: c.textMuted },
    heroTopicName: { fontSize: 17, lineHeight: 25, color: c.text },
    heroTopicArrow: { color: c.brand },
    heroTopicIcon: { color: c.brand },
    qualityCard: { ...panel(c), padding: 16 },
    qualityTitle: { fontSize: 17 },
    qualityText: caption,
    groupCard: { ...panel(c), padding: 16 },
    groupTitle: { fontSize: 17, lineHeight: 25 },
    groupMeta: caption,
    sectionTitle,
    groupOpenButton: secondary(c),
    groupPracticeButton: primary,
    stickyFooter: {
      backgroundColor: c.chrome,
      borderTopWidth: hairline,
      borderTopColor: c.border,
      padding: 16,
    },
    stickyGenerateButton: primary,
    stickyGenerateText: { fontSize: 17, fontWeight: "600" },
    questionCard: { ...panel(c), padding: 16 },
    questionText: { fontSize: 17, lineHeight: 28 },
    title: largeTitle,
    primaryButton: primary,
    primaryText: { fontSize: 17, fontWeight: "600" },
    secondaryButton: secondary(c),
    emptyGroups: { ...panel(c), padding: 24 },
    emptyTitle: sectionTitle,
    emptyText: { fontSize: 15, lineHeight: 24 },
  }),
  community: (c) => ({
    leaderboardEntry: { flexDirection: "row", gap: 6, alignItems: "center" },
    header: {
      backgroundColor: c.chrome,
      paddingHorizontal: 20,
      borderBottomWidth: hairline,
      borderBottomColor: c.border,
    },
    title: { fontSize: 22, lineHeight: 30, fontWeight: "700" },
    eyebrow: caption,
    backButtonText: { fontSize: 17, fontWeight: "400" },
    roomCard: { ...panel(c), marginHorizontal: 16, padding: 16 },
    roomTitle: { fontSize: 17, color: c.text },
    roomText: { ...caption, color: c.textMuted },
    roomIcon: {
      backgroundColor: c.brandSoft,
      borderWidth: 0,
      borderRadius: 12,
    },
    roomIconText: { color: c.brand },
    roomStatus: { color: c.success, fontSize: 13 },
    messageContent: {
      paddingHorizontal: 16,
      paddingBottom: 20,
      width: "100%",
      maxWidth: 760,
      alignSelf: "center",
    },
    bubble: {
      backgroundColor: c.surfaceMuted,
      borderWidth: 0,
      borderRadius: 18,
    },
    bubbleOwn: { backgroundColor: c.action },
    messageText: { fontSize: 17, lineHeight: 26 },
    messageTextOwn: { color: c.white },
    messageTimeOwn: { color: c.textMuted },
    authorName: caption,
    composerInput: {
      backgroundColor: c.surfaceMuted,
      borderWidth: 0,
      borderRadius: 22,
      minHeight: 44,
      fontSize: 17,
    },
    composerRow: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: c.chrome,
    },
    sendButton: {
      backgroundColor: c.action,
      width: 44,
      minHeight: 44,
      borderRadius: 22,
    },
    imageButton: { width: 44, height: 44, borderRadius: 22 },
    leaderboardBackdrop: { backgroundColor: c.overlay, padding: 12 },
    leaderboardPanel: { ...sheet, backgroundColor: c.background },
    leaderboardTabs: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      padding: 3,
      gap: 3,
    },
    leaderboardTab: { minHeight: 44, borderRadius: 8, borderWidth: 0 },
    leaderboardTabActive: { backgroundColor: c.surface },
    leaderboardTabText: { fontSize: 14 },
    leaderboardTabTextActive: { color: c.text },
    leaderboardRow: {
      backgroundColor: c.surface,
      padding: 16,
      borderBottomWidth: hairline,
    },
    leaderboardOwnRow: { backgroundColor: c.brandSoft },
    leaderboardName: { fontSize: 17 },
    leaderboardDetail: caption,
    emptyTitle: sectionTitle,
    emptyText: { fontSize: 15, lineHeight: 24 },
  }),
  daily: (c) => ({
    header: {
      backgroundColor: c.chrome,
      paddingHorizontal: 16,
      borderBottomWidth: hairline,
      borderBottomColor: c.border,
    },
    link: { fontSize: 17, fontWeight: "400" },
    title: { fontSize: 17, fontWeight: "600" },
  }),
  study: (c) => ({
    header: {
      backgroundColor: c.chrome,
      borderBottomWidth: hairline,
      paddingHorizontal: 20,
    },
    headerTitle: { fontSize: 20, lineHeight: 28, fontWeight: "700" },
    actionText: { fontSize: 17, fontWeight: "400" },
    content: page,
    title: largeTitle,
    sectionTitle,
    label: { fontSize: 15, lineHeight: 24 },
    lead: { ...panel(c), padding: 20 },
    feature: { ...panel(c), padding: 16 },
    courseRow: {
      backgroundColor: c.surface,
      padding: 16,
      borderRadius: 14,
      marginBottom: 8,
      borderBottomWidth: 0,
    },
    courseTitle: { fontSize: 17, lineHeight: 26 },
    search: {
      backgroundColor: c.surfaceMuted,
      borderWidth: 0,
      borderRadius: 12,
      fontSize: 17,
    },
    chapterButton: { ...secondary(c), minHeight: 44 },
    chapterSelected: { backgroundColor: c.brandSoft },
    tabs: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 10,
      padding: 3,
      gap: 3,
    },
    tab: { minHeight: 44, borderRadius: 8 },
    tabSelected: { backgroundColor: c.surface },
    tabText: { fontSize: 15 },
    tabSelectedText: { color: c.text },
    footer: { backgroundColor: c.chrome, borderTopWidth: hairline },
    primaryButton: { backgroundColor: c.action, borderRadius: 14 },
    primaryButtonText: { color: c.white, fontSize: 17, fontWeight: "600" },
    secondaryButton: secondary(c),
    question: { ...panel(c), padding: 20 },
    input: {
      backgroundColor: c.background,
      borderWidth: 0,
      borderRadius: 12,
      fontSize: 17,
    },
    sheetBackdrop: {
      backgroundColor: c.overlay,
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    sheet: { borderRadius: 24, maxWidth: 760, backgroundColor: c.background },
    sheetHeader: { paddingVertical: 16 },
    teacherQuestion: {
      backgroundColor: c.brandSoft,
      color: c.text,
      borderRadius: 18,
    },
    teacherComposer: { backgroundColor: c.chrome, borderTopWidth: hairline },
    teacherInput: { backgroundColor: c.surface, fontSize: 17 },
  }),
  redeem: (c) => ({
    nav: { backgroundColor: c.chrome, borderBottomWidth: hairline },
    navTitle: { fontSize: 17, fontWeight: "600" },
    content: { ...page, maxWidth: 640 },
    title: largeTitle,
    eyebrow: caption,
    subtitle: { fontSize: 15, lineHeight: 24 },
    form: { ...panel(c), padding: 20 },
    input: {
      backgroundColor: c.background,
      borderWidth: 0,
      borderRadius: 12,
      fontSize: 17,
    },
    button: primary,
    buttonText: { fontSize: 17, fontWeight: "600" },
    hint: caption,
    success: { ...panel(c), padding: 24 },
    successTitle: sectionTitle,
    successText: { fontSize: 15, lineHeight: 24 },
    historyTitle: sectionTitle,
    historyRow: { ...panel(c), padding: 16, marginBottom: 8 },
    recordTitle: { fontSize: 17 },
    recordMeta: caption,
  }),
  alert: (c) => ({
    backdrop: { backgroundColor: c.overlay },
    card: {
      width: "100%",
      maxWidth: 300,
      padding: 0,
      gap: 0,
      borderRadius: 16,
      overflow: "hidden",
    },
    copy: { padding: 22, gap: 8 },
    title: {
      fontSize: 17,
      lineHeight: 24,
      fontWeight: "600",
      textAlign: "center",
    },
    message: {
      fontSize: 14,
      lineHeight: 21,
      color: c.text,
      textAlign: "center",
    },
    actions: { gap: 0 },
    button: {
      backgroundColor: "transparent",
      borderRadius: 0,
      borderTopWidth: hairline,
      borderTopColor: c.border,
      minHeight: 48,
      padding: 12,
    },
    buttonText: { color: c.brand, fontSize: 17, fontWeight: "400" },
    cancel: { backgroundColor: "transparent" },
    cancelText: { color: c.brand, fontWeight: "600" },
  }),
  brand: () => ({
    seal: { transform: [], borderRadius: 12 },
    compactSeal: { borderRadius: 9 },
    wordmark: { fontSize: 23, fontWeight: "600", letterSpacing: 0 },
  }),
  install: (c) => ({
    button: {
      backgroundColor: c.surface,
      borderWidth: 0,
      borderRadius: 14,
      minHeight: 50,
    },
    buttonText: { fontSize: 17, fontWeight: "400" },
    backdrop: { backgroundColor: c.overlay, padding: 16 },
    card: { ...sheet, padding: 24, maxWidth: 440 },
    title: { fontSize: 24, lineHeight: 32 },
    primary,
    primaryText: { fontSize: 17, fontWeight: "600" },
  }),
};
